services:
  api_v1:
    platform: linux/amd64   # ← forzar emulación amd64 en Apple Silicon
    build:
      context: ./api/v1
      dockerfile: Dockerfile
    volumes:
      - ./api/v1/app/:/app/
      - ./data/qgis/:/app/data/
    working_dir: /app
    ports:
      - "8400:8400"
    environment:
      API_ILI_URL: http://api-ili:8080
      API_ILI_ADMIN_USER: ${ILI_API_ADMIN_USER:-admin}
      API_ILI_ADMIN_PASSWORD: ${ILI_API_ADMIN_PASSWORD:-changeme}
  

  qgis-server-v1:
    image: camptocamp/qgis-server:3.44
    ports:
    - 8300:80
    volumes:
    - ./data/qgis/qgis-server-v1:/data:ro
    environment:
    - LANG=en_EN.UTF-8
    - QGIS_PROJECT_FILE=/data/proyecto.qgz
    - QGIS_SERVER_LOG_LEVEL=0
    - DEBUG=1

  qgis-server-v2:
    image: camptocamp/qgis-server:3.44
    ports:
    - 8200:80
    volumes:
    - ./data/qgis/qgis-server-v2:/data:ro
    environment:
    - LANG=en_EN.UTF-8
    - QGIS_PROJECT_FILE=/data/proyecto.qgz
    - QGIS_SERVER_LOG_LEVEL=0
    - DEBUG=1

  db:
    image: postgis/postgis:18-3.6-alpine
    restart: always
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
    ports:
      - "5533:5432"
    environment:
      - POSTGRES_DB=CHIQUINQUIRA
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=chiquinquira